window.WINE_NOTES = [
  {
    id: 1,
    title: "샴페인 블랑 드 블랑",
    author: "지민",
    style: "Sparkling",
    region: "프랑스",
    body: "드라이한 산미와 섬세한 버블이 깔끔하게 이어지는 노트. 해산물 페어링 추천.",
    score: "98.7",
    views: "8.2k",
    likes: "312",
    saves: "128",
    comments: "+41",
    period: ["week", "month", "all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Champagne_Leclerc_Briant_Abyss.jpg/330px-Champagne_Leclerc_Briant_Abyss.jpg",
    description:
      "첫 모금에서 산도와 기포가 선명하게 올라오는 스타일. 식전주로도 좋고, 굴이나 조개류와 궁합이 좋다는 반응이 많았다.",
    tasting: ["브리오슈", "시트러스", "미세한 버블"],
    pairing: "굴, 조개, 연어 카르파초",
    note: "주간 조회수와 저장 수가 모두 높아 상위권 유지",
  },
  {
    id: 2,
    title: "프로방스 로제",
    author: "수아",
    style: "Rosé",
    region: "프랑스",
    body: "딸기와 허브 뉘앙스가 가볍고 상큼하게 흐르는 노트. 여름용 입문 추천.",
    score: "97.9",
    views: "7.4k",
    likes: "281",
    saves: "102",
    comments: "+35",
    period: ["week", "month", "all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Cuv%C3%A9e_Ros%C3%A9_de_Saign%C3%A9e.jpg/330px-Cuv%C3%A9e_Ros%C3%A9_de_Saign%C3%A9e.jpg",
    description:
      "로제 특유의 산뜻함을 잘 살린 노트로, 국내 사용자들이 자주 찾는 '가볍게 시작하기 좋은 와인' 느낌에 가깝다.",
    tasting: ["딸기", "허브", "라임 제스트"],
    pairing: "샐러드, 치킨, 가벼운 파스타",
    note: "공유가 많아 신규 유입을 가장 많이 만든 카드",
  },
  {
    id: 3,
    title: "피노 누아르 리저브",
    author: "현우",
    style: "Red",
    region: "부르고뉴",
    body: "체리, 버섯, 흙내음이 균형 있게 이어지는 노트. 문장 정리가 좋아 읽기 편함.",
    score: "96.8",
    views: "6.6k",
    likes: "244",
    saves: "96",
    comments: "+29",
    period: ["week", "month", "all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Bottle_and_glass_of_Barefoot_white_zinfandel_wine%2C_2012.jpg/330px-Bottle_and_glass_of_Barefoot_white_zinfandel_wine%2C_2012.jpg",
    description:
      "무겁지 않은 레드라는 점이 강점이다. 향 설명이 정리되어 있어 초보자도 읽기 어렵지 않다.",
    tasting: ["체리", "버섯", "가죽"],
    pairing: "버섯 리조또, 구운 오리",
    note: "메모형 설명이 잘 정리된 카드",
  },
  {
    id: 4,
    title: "소비뇽 블랑",
    author: "서연",
    style: "White",
    region: "뉴질랜드",
    body: "허브, 라임, 자몽 향이 선명한 산뜻한 노트. 바디가 가벼워 초보자 반응이 좋음.",
    score: "95.2",
    views: "5.9k",
    likes: "211",
    saves: "88",
    comments: "+22",
    period: ["week", "month", "all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/WineBottles_20230715_191850.jpg/330px-WineBottles_20230715_191850.jpg",
    description:
      "산미가 앞에 있고 뒤맛이 깨끗하게 끝나는 스타일. 국내에서 '회식/캠핑용 화이트'로 많이 소비되는 타입과 유사하다.",
    tasting: ["허브", "라임", "자몽"],
    pairing: "회, 초밥, 닭가슴살",
    note: "가장 무난하게 클릭되는 입문형 카드",
  },
  {
    id: 5,
    title: "브뤼 나뚜르",
    author: "민재",
    style: "Sparkling",
    region: "이탈리아",
    body: "브리오슈와 사과 향이 또렷하고 마무리가 정돈된 노트. 깔끔한 요약이 장점.",
    score: "94.9",
    views: "5.4k",
    likes: "198",
    saves: "77",
    comments: "+18",
    period: ["month", "all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Champagne_bottle%2C_2015-%2801%29.jpg/330px-Champagne_bottle%2C_2015-%2801%29.jpg",
    description:
      "주간보다 월간에서 반응이 안정적으로 쌓이는 카드. 한 번 읽으면 저장하는 비율이 높은 편이다.",
    tasting: ["사과", "브리오슈", "레몬"],
    pairing: "튀김, 치즈, 브런치",
    note: "저장 수가 꾸준한 카드",
  },
  {
    id: 6,
    title: "비오니에 블렌드",
    author: "지우",
    style: "White Blend",
    region: "미국",
    body: "살구와 꽃향이 살아 있는 노트. 향 묘사가 좋아서 저장 전환율이 높음.",
    score: "94.1",
    views: "4.8k",
    likes: "177",
    saves: "70",
    comments: "+16",
    period: ["month", "all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Schramsberg_Vineyards%2C_July_2019-7563%2B7565.jpg/330px-Schramsberg_Vineyards%2C_July_2019-7563%2B7565.jpg",
    description:
      "향 중심의 설명이 많아서 테이스팅 초점이 분명하다. 국내 사용자 입장에서는 '향 좋은 화이트'로 빠르게 이해된다.",
    tasting: ["살구", "아카시아", "배"],
    pairing: "크림 파스타, 흰 살 생선",
    note: "향 묘사 만족도가 높은 카드",
  },
  {
    id: 7,
    title: "말벡 클래식",
    author: "도현",
    style: "Red",
    region: "아르헨티나",
    body: "블랙베리와 코코아 톤이 선명한 노트. 첫 문단이 짧아서 모바일 가독성이 좋음.",
    score: "93.6",
    views: "4.4k",
    likes: "161",
    saves: "61",
    comments: "+13",
    period: ["month", "all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/2020_10_10_016_Tour_de_Vin.jpg/330px-2020_10_10_016_Tour_de_Vin.jpg",
    description:
      "레드 중에서도 진하지만 문장이 과하지 않다. 바디감과 과실감 중심으로 바로 읽히는 구조다.",
    tasting: ["블랙베리", "코코아", "바닐라"],
    pairing: "스테이크, 바비큐",
    note: "진한 과실 좋아하는 사람에게 강함",
  },
  {
    id: 8,
    title: "샤르도네 오크 숙성",
    author: "유진",
    style: "White",
    region: "칼리포니아",
    body: "바닐라, 토스트, 배 향이 밸런스 있게 정리된 노트. 요약형 문장 구조가 안정적.",
    score: "93.0",
    views: "4.1k",
    likes: "153",
    saves: "59",
    comments: "+12",
    period: ["all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Wine_Bottle_MET_62455.jpg/330px-Wine_Bottle_MET_62455.jpg",
    description:
      "월간/전체에서 꾸준히 들어오는 카드. 오크감이 있는 화이트를 찾는 사용자에게는 바로 이해되는 분류다.",
    tasting: ["바닐라", "토스트", "배"],
    pairing: "치킨, 버터 파스타",
    note: "월간에서 꾸준히 상위에 남는 타입",
  },
  {
    id: 9,
    title: "크레망 드 부르고뉴",
    author: "민서",
    style: "Sparkling",
    region: "부르고뉴",
    body: "견과류와 시트러스가 교차하는 고전적인 노트. 댓글이 꾸준히 붙는 타입.",
    score: "92.4",
    views: "3.9k",
    likes: "142",
    saves: "53",
    comments: "+11",
    period: ["all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Tsimlyansk_wines%2C_Wine_bottles%2C_Rostov-on-Don%2C_Russia.jpg/330px-Tsimlyansk_wines%2C_Wine_bottles%2C_Rostov-on-Don%2C_Russia.jpg",
    description:
      "검색에서 자주 유입되는 유형의 클래식 스파클링. 설명이 짧아도 핵심이 잘 전달된다.",
    tasting: ["견과류", "시트러스", "브리오슈"],
    pairing: "튀김, 생선, 치즈 플래터",
    note: "고전형 스파클링 노트",
  },
  {
    id: 10,
    title: "카베르네 소비뇽",
    author: "태오",
    style: "Red",
    region: "칠레",
    body: "블랙커런트와 시더 톤이 정갈한 노트. 상위권 진입 직전의 성장형 콘텐츠.",
    score: "91.8",
    views: "3.6k",
    likes: "131",
    saves: "48",
    comments: "+9",
    period: ["all"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Wine_Bottle_MET_ADA4147.jpg/330px-Wine_Bottle_MET_ADA4147.jpg",
    description:
      "레드 입문자와 중급자 사이를 넓게 받는 콘텐츠. 아직 위로 더 올라갈 여지가 보여 성장형으로 분류했다.",
    tasting: ["블랙커런트", "시더", "오크"],
    pairing: "양갈비, 육회, 치즈",
    note: "순위 상승 여지가 있는 후보",
  },
];
